version: '3'

volumes:
  bravo11_local_postgres_data: {}
  bravo11_local_postgres_data_backups: {}
  opensearch-data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bravo11_local_django
    container_name: bravo11_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bravo11_production_postgres
    container_name: bravo11_local_postgres
    volumes:
      - bravo11_local_postgres_data:/var/lib/postgresql/data
      - bravo11_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: bravo11_local_redis
